IF DB_ID('productos') IS NOT NULL
BEGIN
    ALTER DATABASE productos SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE productos;
END
GO

CREATE DATABASE productos;
GO

USE productos;
GO

CREATE TABLE LAPTOPS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,
    STOCK INT NOT NULL
);
GO

INSERT INTO LAPTOPS (NOMBRE, PRECIO, STOCK) VALUES 
('Laptop Dell Inspiron 15', 899.99, 10),
('Laptop HP Pavilion', 749.99, 15),
('Laptop Lenovo ThinkPad', 1099.99, 8),
('Laptop ASUS VivoBook', 599.99, 20);
GO

SELECT * FROM LAPTOPS;
